### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by ntsirakis**
Not sure if any of these changes are desired. I've been using them locally and figured I'd PR them in case there's an interest.

### CODE REVIEW

**Comment by dpsmith** [comment]
I like the docker_deploy and if you break that out separately I would be glad to merge it.

As for abstracting out the `-i` flag, that is why there is this [check](https://github.com/apertussolutions/bordel/blob/master/bordel#L55). The idea was to eventually add a command/subcommand called `select` or similar that would automatically set the symlink. For now I just manually set the link from `build` to `build-{BUILDID}`. If there is some additional benefit I missed to your approach, please PR it separately and let us know why. @eric-ch and I can review and provide you feedback or accept it.

**Comment by ntsirakis** [comment]
> I like the docker_deploy and if you break that out separately I would be glad to merge it.

Can do.

> As for abstracting out the `-i` flag, that is why there is this [check](https://github.com/apertussolutions/bordel/blob/master/bordel#L55). The idea was to eventually add a command/subcommand called `select` or similar that would automatically set the symlink. For now I just manually set the link from `build` to `build-{BUILDID}`. If there is some additional benefit I missed to your approach, please PR it separately and let us know why. @eric-ch and I can review and provide you feedback or accept it.

Yeah Eric pointed that out to me, I was wondering what that symlink was for. I was under the assumption that you could have multiple builds active at once, but that does not appear to be the case with all the shared folders. I'll drop this commit.

**Comment by dpsmith** [comment]
The primary focus is to keep all the OE and OpenXT build configuration out of the way of the developers. With that said, I do think we should support doing multiple builds at the same time. If you would like, we can start a thread on openxt-devel or on the slack channel to discuss what changes might be necessary. Then one of us can PR the changes.

**Review by dpsmith — APPROVED** [review]

**Comment by ntsirakis** [comment]
Personally, I think the OE bits are very much tied to a given build and should be kept separate on a build-to-build basis. It's very possible that a developer's changes would lie solely in the meta-layers (e.g. updating a patch queue), and thus it would be impractical to share that metadata with another build (even if it's possible to "activate" a given build). I disagree with keeping them out of the way for that reason.

**Pull request merged**
